# Generated by Django 5.2.15 on 2026-07-27 15:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('jefe_departamento', models.CharField(blank=True, default='', max_length=150)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='', max_length=1)),
                ('direccion', models.TextField(blank=True, default='')),
                ('cargo', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dias_vacaciones_pendientes', models.IntegerField(default=30)),
                ('dias_vacaciones_tomados', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vacaciones', 'En Vacaciones'), ('licencia', 'En Licencia')], default='activo', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='empleados/')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='Vacaciones.departamento')),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('personal', 'Permiso Personal'), ('medico', 'Permiso Médico'), ('luto', 'Luto'), ('maternidad', 'Maternidad/Paternidad'), ('otro', 'Otro')], max_length=20)),
                ('motivo', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_solicitados', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('aprobado_por', models.CharField(blank=True, default='', max_length=150)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='Vacaciones.empleado')),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='TurnoGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.CharField(choices=[('manana', 'Mañana (06:00-14:00)'), ('tarde', 'Tarde (14:00-22:00)'), ('noche', 'Noche (22:00-06:00)')], max_length=10)),
                ('horas', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_por', models.CharField(blank=True, default='', max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='Vacaciones.empleado')),
            ],
            options={
                'ordering': ['fecha', 'turno'],
                'unique_together': {('empleado', 'fecha', 'turno')},
            },
        ),
        migrations.CreateModel(
            name='Sustitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('empleado_sustituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustituciones_como_sustituto', to='Vacaciones.empleado')),
                ('turno_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustituciones_originales', to='Vacaciones.turnoguardia')),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
